#!/bin/bash
set -v
java CalendarHighlight 1 28 5
java CalendarHighlight 6 31 16
java CalendarHighlight 6 31 4
java CalendarHighlight 8 28 14
java CalendarHighlight 0 31 4
java CalendarHighlight 5 24 26
java CalendarHighlight 5 25 15
java CalendarHighlight 2 99 45
java CalendarHighlight 2 100 45
