#!/bin/bash
set -v
java CompareQuadPoly 1 2 3 4 5 6
java CompareQuadPoly 2 2 2 2 2 2
java CompareQuadPoly 0 0 0 0 0 0
java CompareQuadPoly 0 0 0 1 1 1
java CompareQuadPoly 0 1 0 2 3 4
java CompareQuadPoly 1 1 0 1 3 0
java CompareQuadPoly -1 -1 0 -1 -3 0
java CompareQuadPoly -1 -1 0 1 3 0
java CompareQuadPoly 5 5 5 5 5 4
java CompareQuadPoly 5 5 5 5 5 6
